language: ruby
matrix:
  include:
    - rvm: 2.2
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_5_2.gemfile
cache:
  - bundler
script: "bundle exec rake spec"
