language: ruby
services:
  - postgresql
matrix:
  include:
    - rvm: 2.4.5
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5_2.gemfile
cache:
  - bundler
script: "bundle exec rake"
